tunnel:
  enable: true
  connectNet: 10.10.
  adressPool: 12.12.12.0
  adressPrefix: 24
  image: 8548388
  localDev: ens18
  remoteDev: eth0
  remoteHost: 91.149.218.39

bgp:
  enable: true
  adressPool: 11.11.11.0
  adressPrefix: 24
  localAsn: 66000
  remoteAsn:
    - name: as-1
      asn: 66001
      ip: 191.168.111.1

l2:
  enable: true
  adressPool: 13.13.13.0
  adressPrefix: 24
  localDev: ens18