---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp-lb
spec:
  bgpInstances:
  - name: "external"
    localASN: 66000
    peers:
{{- range $peers := .Values.bgp.remoteAsn }}
    - name: "{{ $peers.name }}"
      peerASN: {{ $peers.asn }}
      peerAddress: {{ $peers.ip }}
      peerConfigRef:
        name: "cilium-peer"
{{- end }}
