---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool-lb
spec:
  blocks:
    - cidr: {{ .Values.bgp.adressPool }}/{{ .Values.bgp.adressPrefix }}
  disabled: false
  serviceSelector:
    matchLabels:
      pool: bgp