{{- if .Values.tun }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: installer
spec:
  selector:
    matchLabels:
      job: installer
  template:
    metadata:
      labels:
        job: installer
    spec:
      hostPID: true
      restartPolicy: Always
      containers:
      - image: djsasha777/node-installer:{{ .Values.bgp.image }}
        name: installer
        securityContext:
          privileged: true
        volumeMounts:
        - name: script
          mountPath: /tmp
        - name: host
          mountPath: /host
      volumes:
      - name: script
        configMap:
          name: tun
      - name: host
        hostPath:
          path: /tmp/install
{{- end }}