apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2
spec:
  externalIPs: true
  interfaces:
    - ^ens[0-19]+
  loadBalancerIPs: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  serviceSelector:
    matchLabels:
      pool: l2
