apiVersion: v1
kind: ConfigMap
metadata:
  name: tun
data:
  preinit.sh: |
    #!/usr/bin/env bash
    if [ ! -f "LOCALINIT" ]; then
    echo "LOCAL INIT START"
    sysctl -w net.ipv4.ip_forward=1
    if ! grep -q '^PermitTunnel yes$' /etc/ssh/sshd_config; then
    echo 'PermitTunnel yes' | sudo tee -a /etc/ssh/sshd_config > /dev/null
    service ssh restart
    sleep 5
    apt update && apt install -y --fix-missing expect bird net-tools && touch LOCALINIT
    fi
    else
    echo "LOCAL is already initialized"
    fi
    if [ ! -f "REMOTEINIT" ]; then
    echo "REMOTE INIT START"
    if [ ! -f ~/.ssh/id_rsa ]; then
    echo "SSH key generation..."
    ssh-keygen -t rsa -b 4096 -N "" -f ~/.ssh/id_rsa
    fi
    expect -c "spawn ssh-copy-id root@{{ .Values.connect.remoteHost }}
    expect \"password:\"
    send \"{{ .Values.connect.remoteSshPass }}\r\"
    interact"
    ssh root@{{ .Values.connect.remoteHost }} "apt update \
    apt install -y --fix-missing haproxy bird && \
    sysctl -w net.ipv4.ip_forward=1 && \
    if ! grep -q '^PermitTunnel yes$' /etc/ssh/sshd_config; then
    echo 'PermitTunnel yes' | sudo tee -a /etc/ssh/sshd_config > /dev/null
    systemctl restart sshd
    sleep 5
    fi"
    touch REMOTEINIT    
    else
    echo "REMOTE is already initialized"
    fi
  init.sh: |
    #!/usr/bin/env bash
    LOCIP=$(ifconfig {{ .Values.connect.localDev }} | grep 'inet' | awk '{print $2}' | cut -d '.' -f 4 | sed '1q')
    sed -i 's/NUM/$LOCIP/g' /tmp/install/install.sh
  install.sh: |
    #!/usr/bin/env bash
    ssh -w NUM:NUM -f {{ .Values.connect.remoteHost }} -p 22 "\
    ip link set tunNUM up && true ip addr add {{ .Values.connect.net}}NUM.1/30 \
    dev tunNUM && ip link set tunNUM up && true"
    sleep 5
    ip addr add "{{ .Values.connect.net }}NUM.NUM/30" dev tunNUM && ip link set tunNUM up

    