apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-installer-config
data:
  install.sh: |
    #!/usr/bin/env bash
    #LOCAL INIT
    if [ ! -f "LOCALINIT" ]; then
    echo "LOCAL INIT START"
    sysctl -w net.ipv4.ip_forward=1
    apt update && apt install expect bird -y --fix-missing
    fuser /var/{lib/{dpkg,apt/lists},cache/apt/archives}/lock >/dev/null 2>&1; do sleep 1; done
    if ! grep -q '^PermitTunnel yes$' /etc/ssh/sshd_config; then
    echo 'PermitTunnel yes' | sudo tee -a /etc/ssh/sshd_config > /dev/null
    service ssh restart
    sleep 5
    touch LOCALINIT
    fi
    else
    echo "LOCAL Уже инициализировано"
    fi
    #REMOTE INIT
    if [ ! -f "REMOTEINIT" ]; then
    echo "REMOTE INIT START"
    if [ ! -f ~/.ssh/id_rsa ]; then
    echo "Генерация нового SSH-ключа..."
    ssh-keygen -t rsa -b 4096 -N "" -f ~/.ssh/id_rsa
    fi
    expect -c "spawn ssh-copy-id root@{{ .Values.connect.remoteHost }}
    expect \"password:\"
    send \"{{ .Values.connect.remoteSshPass }}\r\"
    interact"
    ssh root@{{ .Values.connect.remoteHost }} "\
    apt update && apt install haproxy bird -y --fix-missing && \
    fuser /var/{lib/{dpkg,apt/lists},cache/apt/archives}/lock >/dev/null 2>&1; do sleep 1; done && \
    sysctl -w net.ipv4.ip_forward=1 && \
    if ! grep -q '^PermitTunnel yes$' /etc/ssh/sshd_config; then
    echo 'PermitTunnel yes' | sudo tee -a /etc/ssh/sshd_config > /dev/null
    systemctl restart sshd
    sleep 5
    touch REMOTEINIT
    fi"      
    else
    echo "REMOTE Уже инициализировано"
    fi
    #TUNNEL
    ssh -w 0:0 -f {{ .Values.connect.remoteHost }} -p 22 "if ip link show | grep -q 'tun0'; then \
      echo "Интерфейс tun0 уже существует." \
    else \
      ip addr add {{ .Values.connect.remoteHost}}/{{ .Values.connect.remoteMask}} dev tun0 && ip link set tun0 up && true \
    fi"
    sleep 5
    LOCIP=$(ifconfig {{ .Values.connect.localDev }} | grep 'inet' | awk '{print $2}' | cut -d '.' -f 4 | sed '1q')
    if ip link show | grep -q 'tun0'; then
      echo "Интерфейс tun0 уже существует."
    else
      ip addr add {{ .Values.connect.localIp }}$LOCIP/{{ .Values.connect.localMask }} dev tun0 && ip link set tun0 up
    fi
    