apiVersion: v1
kind: ConfigMap
metadata:
  name: tun
data:
  softinstall.sh: |
    #!/usr/bin/env bash
{{- if .Values.tun }}
    apt update && apt install -y --fix-missing expect bird net-tools
{{- else }}
    echo "none"
{{- end }}
  preinit.sh: |
    #!/usr/bin/env bash
{{- if .Values.tun }}
    if [ ! -f "LOCALINIT" ]; then
    echo "LOCAL INIT START"
    sysctl -w net.ipv4.ip_forward=1
    echo 'PermitTunnel yes' | sudo tee -a /etc/ssh/sshd_config > /dev/null
    echo "SSH key generation..."
    ssh-keygen -t rsa -b 4096 -N "" -f ~/.ssh/id_rsa
    service ssh restart
    sleep 5
    touch LOCALINIT
    fi
    else
    echo "LOCAL is already initialized"
    fi
    if [ ! -f "REMOTEINIT" ]; then
    echo "REMOTE INIT START"
    expect -c "spawn ssh-copy-id root@{{ .Values.connect.remoteHost }}
    expect \"password:\"
    send \"{{ .Values.connect.remoteSshPass }}\r\"
    interact"
    ssh root@{{ .Values.connect.remoteHost }} "apt update && apt install -y --fix-missing haproxy bird
    sysctl -w net.ipv4.ip_forward=1
    echo 'PermitTunnel yes' | sudo tee -a /etc/ssh/sshd_config > /dev/null
    systemctl restart sshd
    sleep 5"
    touch REMOTEINIT    
    else
    echo "REMOTE is already initialized"
    fi
{{- else }}
    echo "none"
{{- end }}
  init.sh: |
    #!/usr/bin/env bash
{{- if .Values.tun }}
    LOCIP=$(ifconfig {{ .Values.connect.localDev }} | grep 'inet' | awk '{print $2}' | cut -d '.' -f 4 | sed '1q')
    sed -i 's/NUM/$LOCIP/g' /tmp/install/install.sh
{{- else }}
    echo "none"
{{- end }}
  install.sh: |
    #!/usr/bin/env bash
{{- if .Values.tun }}
    ssh -w NUM:NUM -f {{ .Values.connect.remoteHost }} -p 22 "\
    ip link set tunNUM up && true ip addr add {{ .Values.connect.net}}NUM.1/30 \
    dev tunNUM && ip link set tunNUM up && true"
    sleep 5
    ip addr add "{{ .Values.connect.net }}NUM.NUM/30" dev tunNUM && ip link set tunNUM up
{{- else }}
    echo "none"
{{- end }}