---
apiVersion: v1
kind: ConfigMap
metadata:
  name: script
data:
  script.sh: |
    #!/usr/bin/env bash
    sysctl -w net.ipv4.ip_forward=1
    if ! grep -q '^PermitTunnel yes$' /etc/ssh/sshd_config; then
      echo "PermitTunnel yes" | sudo tee -a /etc/ssh/sshd_config > /dev/null
      echo "ADDED 'PermitTunnel yes' TO /etc/ssh/sshd_config."
    else
      echo "THE 'PermitTunnel yes' IS IN FILE /etc/ssh/sshd_config."
    fi
    ssh -w 0:0 -f {{ .Values.connect.remoteHost }} -p 22 "ip addr add {{ .Values.connect.remoteHost}}/{{ .Values.connect.remoteMask}} dev tun0 && ip link set tun0 up && true"
    sleep 3
    LOCIP=$(ifconfig {{ .Values.connect.localDev }} | grep 'inet' | awk '{print $2}' | cut -d '.' -f 4 | sed '1q')
    ip addr add {{ .Values.connect.localIp }}$LOCIP/{{ .Values.connect.localMask }} dev tun0 && ip link set tun0 up