apiVersion: v1
kind: Service
metadata:
  name: nginxbgp
  labels:
    pool: bgp
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30466
  selector:
    app: nginx
  type: LoadBalancer