apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    pool: l2
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30454
  selector:
    app: nginx
  type: LoadBalancer
  loadBalancerClass: io.cilium/l2-announcer