{{- if .Values.watcher.enable }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: watcher
subjects:
- kind: ServiceAccount
  name: default
  namespace: tunnel
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watcher
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: watcher
    spec:
      containers:
        - name: watcher
          image: djsasha777/watcher:{{ .Values.watcher.image }}
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 500Mi
              
---
apiVersion: v1
kind: Service
metadata:
  name: watcher
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: watcher
{{- end }}