name: tunnel
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: get build number
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
         length: 7
      - name: Get git commit data
        uses: rlespinasse/git-commit-data-action@v1    
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set Docker tag
        id: tag
        uses: cytopia/docker-tag-action@v0.4.7
        with:
          latest_git_branch: master
          latest_docker_tag_name: ${{ matrix.version }}
          non_latest_docker_tag_prefix: "${{ matrix.version }}-"    
      - name: Build ni
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ni/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tunnel:${{ steps.tag.outputs.docker-tag }}
      - name: Build wa
        uses: docker/build-push-action@v3
        with:
          context: .
          file: wa/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/watcher:${{ steps.tag.outputs.docker-tag }}