name: tunnel
on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: get build number
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
         length: 7
      - name: Get git commit data
        uses: rlespinasse/git-commit-data-action@v1    
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/tunnel       
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha 
      - name: Build ni
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ni/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tunnel:${{ steps.meta.outputs.tags }}
      - name: Build wa
        uses: docker/build-push-action@v3
        with:
          context: .
          file: wa/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/watcher:${{ steps.meta.outputs.tags }}